### ISSUE TITLE
They don't believe me

### ISSUE THREAD

**Issue by ShadowMario** [bbpanzu/APOLOGY-101#1]
What i should do

**Comment by mariosbignuts** [comment]
force them to

**Comment by bbpanzu** [comment]
the issue should be fixed now

**Comment by tposejank** [comment]
epic

**Comment by SkyanUltra** [comment]
i tried to hold them by gunpoint to get them to believe me but they still dont and now they don't like me even more than before, and im not sure why. what should i do to try and get them to believe me more?

**Comment by ShadowMario** [comment]
Forgot to close this thanks guys
